### ISSUE TITLE
Question about SX1303

### ISSUE THREAD

**Issue by pablogranolabar** [RAKWireless/udp-packet-forwarder#6]
Hi!

I am working on a LoRa mesh networking project that is similar to Helium mining in nature, except the network Proof of Work is providing exit node services for IPFS pub sub.

So for example 25 handheld devices on a college campus, each device has dual SX1262 LoRa radios (primary radio is for IM and blockchain transactions, second radio is control channel). So I am not using a conventional LoRaWAN architecture with this but rather a BLE-based method of providing exit node services via an iOS or Android app.

I am exploring standalone configurations for this based on the [RAK 5146](https://store.rakwireless.com/products/rak5146-kit?variant=41577988194502) which has a GPS and SX1303. I am curious if your UDP packet forwarder could be used in this instance, to flush the local LoRa networks' message queues using these handheld devices, e.g.  whenever a handheld device gets into range of the SX1303, to send gRPC traffic to that node to conduct IPFS pubsub transactions?

How does this forwarder present itself at the LoRa level, do I have to be running a LoRaWAN stack on each device or can the device scan for LoRa channels and simply send UDP?

**Comment by xoseperez** [comment]
Hi!
The packet forwarder is meant to send the packets to a LoRaWAN network server. If you want to access the raw packets at the concentrator you might want to check the HAL instead: https://github.com/Lora-net/sx1302_hal and build your solution on top of it.

**Comment by xoseperez** [comment]
Closing this.
