### ISSUE TITLE
No image for linux/arm/v6

### ISSUE THREAD

**Issue by lenwevader** [RAKWireless/udp-packet-forwarder#9]
Although the README claims support for ARMv6 `docker compose up` results in `no matching manifest for linux/arm/v6 in the manifest list entries`. Indeed, no ARMv6 images are present on Docker Hub. I am trying to run on a Raspberry Pi 1 B+. Is it possible to add prebuilt images for ARMv6 support? I tried building my own with ` docker buildx bake --load arm`, but it failed.

**Comment by xoseperez** [comment]
Hi @lenwevader 
The latest version (v2.2.0) includes an image for armv6l devices.
